version: "3.9"	

services:	

  portainer:	
    container_name: ${HOSTNAME}
    image: portainer/portainer-ce	
    restart: unless-stopped	
    ports:	
      - ${PORT_HTTP}:8000	
      - ${PORT_HTTPS}:9443	
    volumes:	
      - /var/run/docker.sock:/var/run/docker.sock:ro	
      - ${VOLUME}/localtime:/etc/localtime:ro	
      - ${VOLUME}/timezone:/etc/timezone:ro	
      - ${VOLUME}/data:/data	
    networks:	
      frontend:
       ipv4_address: 192.168.0.4

networks:
  frontend:
    name: frontend
    external: true