FROM wordpress:latest

LABEL maintener="Otaku"

RUN apt-get update --no-cache && \
apt-get install -y  --no-install-recommends ssl-cert && \
a2enmod ssl && \
a2ensite default-ssl && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

